name: reverse_beacon
description: transforms the reverse beacon telnet CW and DIGI servers into a controllable stream 
version: 1.0.3
repository: https://github.com/N1BRI/reverse_beacon

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
